"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { date } from "../../_lib/format";
import { careerCategories, careerFilterSearch, filterFootballCareers, parseCareerFilters, sortFootballCareers, type CareerCategory, type CareerIndex, type CareerSort } from "../../_lib/football-careers";

const labels: Record<CareerCategory, string> = { all: "All identified players", passing: "Passing EPA", rushing: "Rushing EPA", receiving: "Receiving EPA", defensive: "Defensive events", interceptions: "Interceptions", fumbles: "Fumbles", kicking: "Kicking", punting: "Punting", kickReturns: "Kick returns", puntReturns: "Punt returns" };
const compact = (value: number | null | undefined, digits = 1) => value == null || !Number.isFinite(value) ? "—" : value.toFixed(digits);

export default function CareerBrowser() {
  const initial = typeof window === "undefined" ? null : parseCareerFilters(window.location.search);
  const [query, setQuery] = useState(initial?.filters.query || ""), [category, setCategory] = useState<CareerCategory>(initial?.filters.category || "passing"), [division, setDivision] = useState<"all" | "fbs" | "fcs">(initial?.filters.division || "fbs"), [minSeasons, setMinSeasons] = useState(initial?.filters.minSeasons || 1), [sort, setSort] = useState<CareerSort>(initial?.sort || "epa"), [page, setPage] = useState(initial?.page || 0), [data, setData] = useState<CareerIndex | null>(null), [error, setError] = useState("");
  useEffect(() => { fetch("/data/football/player-careers.json").then((r) => { if (!r.ok) throw Error("The cross-season player archive is unavailable."); return r.json() as Promise<CareerIndex>; }).then(setData).catch((e) => setError(e.message)); }, []);
  useEffect(() => { const search = careerFilterSearch({ query, category, division, minSeasons }, sort, page); window.history.replaceState(window.history.state, "", `${window.location.pathname}${search}`); }, [category, division, minSeasons, page, query, sort]);
  const rows = useMemo(() => data ? sortFootballCareers(filterFootballCareers(data.players, { query, category, division, minSeasons }), category, sort) : [], [category, data, division, minSeasons, query, sort]);
  const shown = rows.slice(page * 40, page * 40 + 40), pageCount = Math.max(1, Math.ceil(rows.length / 40));
  const reset = <T,>(setter: (value: T) => void, value: T) => { setter(value); setPage(0); };
  return <>{error ? <p className="status-error" role="alert">{error}</p> : !data ? <p className="empty" role="status">Loading nine seasons of player records…</p> : <>
    <div className="strip"><div><strong>{data.coverage.player_count.toLocaleString()}</strong><span>Identified source athletes</span></div><div><strong>{data.coverage.source_records.toLocaleString()}</strong><span>Season/team records</span></div><div><strong>{data.coverage.seasons.length}</strong><span>Source seasons · {data.coverage.seasons[0]}–{data.coverage.seasons.at(-1)}</span></div><div><strong>{rows.length.toLocaleString()}</strong><span>Players in this view</span></div></div>
    <div className="toolbar"><label className="control"><span>PLAYER OR PROGRAM</span><input type="search" value={query} maxLength={120} placeholder="Search a player, team or conference" onChange={(e) => reset(setQuery, e.target.value)} /></label><label className="control"><span>CATEGORY</span><select value={category} onChange={(e) => reset(setCategory, e.target.value as CareerCategory)}>{careerCategories.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label><label className="control"><span>DIVISION</span><select value={division} onChange={(e) => reset(setDivision, e.target.value as typeof division)}><option value="fbs">FBS</option><option value="fcs">FCS</option><option value="all">All imported divisions</option></select></label><label className="control"><span>MINIMUM SEASONS</span><select value={minSeasons} onChange={(e) => reset(setMinSeasons, Number(e.target.value))}>{[1, 2, 3, 4].map((value) => <option key={value} value={value}>{value}+ season{value === 1 ? "" : "s"}</option>)}</select></label><label className="control"><span>ORDER</span><select value={sort} onChange={(e) => reset(setSort, e.target.value as CareerSort)}><option value="epa">Career total EPA</option><option value="plays">Career plays</option><option value="seasons">Most seasons</option><option value="games">Most box games</option><option value="name">Player name</option></select></label></div>
    <p className="note">Career totals add only within the selected source category. A player may have multiple source team records in one season; those records remain visible in the team trail. This index is descriptive and does not infer transfers, eligibility or current roster status.</p>{category === "all" && <p className="note">All-player view intentionally does not add passing, rushing, receiving or event EPA together.</p>}
    <div className="section-heading" style={{ marginBottom: 20 }}><p>{rows.length.toLocaleString()} players · edition {date(data.generated_at)}</p><a className="hero-link" href="/data/football/player-careers.json">Download career index ↗</a></div>
    <div className="table-scroll"><table className="data-table"><thead><tr><th>Player / source ID</th><th>Team trail</th><th className="numeric">Seasons</th><th className="numeric">Box games</th><th className="numeric">Plays</th><th className="numeric">Yards</th><th className="numeric">TD</th><th className="numeric">Career EPA</th><th className="numeric">EPA / play</th></tr></thead><tbody>{shown.map((player) => { const production = category === "all" ? null : player.production[category]; const latest = player.teams[player.teams.length - 1]; return <tr key={player.id}><td><Link href={`/football/player/?id=${encodeURIComponent(player.id)}&season=${latest?.season || player.last_season}`}>{player.name}</Link><small>Source athlete {player.id}</small><small>{player.first_season}–{player.last_season}</small></td><td>{player.teams.slice(-3).reverse().map((team) => <span key={`${team.season}-${team.team_id}`} className="table-subrow"><strong>{team.team}</strong><small>{team.season} · {team.division || "division unavailable"}{team.conference ? ` · ${team.conference}` : ""}</small></span>)}</td><td className="numeric"><strong>{player.season_count}</strong><small>{player.seasons.join(" · ")}</small></td><td className="numeric">{player.box_games.toLocaleString()}</td><td className="numeric">{production ? compact(production.plays, 0) : "—"}</td><td className="numeric">{production ? compact(production.yards, 0) : "—"}</td><td className="numeric">{production ? compact(production.touchdowns, 0) : "—"}</td><td className="numeric"><strong>{production ? compact(production.epa) : "—"}</strong>{production?.best_rank != null && <small>Best source rank #{production.best_rank}</small>}</td><td className="numeric">{production ? compact(production.epa_per_play, 2) : "—"}</td></tr>; })}</tbody></table></div>
    {!shown.length && <p className="empty">No identified players match these filters.</p>}<div className="pagination"><span>Page {page + 1} of {pageCount}</span><div><button className="button secondary" disabled={!page} onClick={() => setPage(page - 1)}>← Previous</button><button className="button secondary" disabled={(page + 1) * 40 >= rows.length} onClick={() => setPage(page + 1)}>Next →</button></div></div>
    <section className="section paper-panel"><div className="eyebrow">Source boundary</div><h2>One ID, many seasons.</h2><p>{data.methodology}</p><p>Open a player&apos;s season link for the full game log and raw source fields. Negative team-attributed IDs are excluded from this identified career index, while event notebooks remain available for name-attributed defense and specialists.</p><p>Season catalog edition <span className="source-hash">{data.source_catalog_edition || "unavailable"}</span></p><p><Link href="/football/players/">Open the season player index →</Link> · <Link href="/football/events/">Open defensive and specialist events →</Link></p></section>
  </>}</>;
}
