"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { downloadCsv, toCsv } from "../../_lib/csv";
import { fmt } from "../../_lib/format";

type Kind = "ratings" | "players";
type Metric = { key: string; label: string; unit: string };
type Row = { id: string; team: string; abbreviation?: string | null; player?: string | null; team_id?: string; value: number | null; bpm?: number | null };
type Result = { kind: Kind; season: number; metric: Metric; page: number; page_size: number; total: number; non_null: number; rows: Row[] };
function display(value: number | null, metric: Metric) { if (value == null) return "—"; return metric.unit === "rank" ? fmt(value, 0) : fmt(value, 1); }
export default function Boutique() {
  const [kind, setKind] = useState<Kind>("ratings"), [seasons, setSeasons] = useState<number[]>([]), [metrics, setMetrics] = useState<Metric[]>([]);
  const [season, setSeason] = useState("2026"), [metric, setMetric] = useState("rank"), [query, setQuery] = useState(""), [direction, setDirection] = useState<"desc" | "asc">("asc"), [page, setPage] = useState(0);
  const [result, setResult] = useState<Result | null>(null), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch(`/api/basketball/research/boutique?kind=${kind}&meta=1`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The boutique model catalog is unavailable."); return r.json() as Promise<{ seasons: number[]; metrics: Metric[] }>; }).then((p) => { setSeasons(p.seasons); setMetrics(p.metrics); setMetric(p.metrics[0]?.key || ""); if (p.seasons.length && !p.seasons.includes(Number(season))) setSeason(String(p.seasons[0])); }).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [kind]);
  const selected = useMemo(() => metrics.find((m) => m.key === metric) || metrics[0] || null, [metrics, metric]);
  useEffect(() => { if (!selected) return; const controller = new AbortController(); setResult(null); setError(""); const params = new URLSearchParams({ kind, season, metric: selected.key, page: String(page), direction }); if (query.trim()) params.set("q", query.trim()); fetch(`/api/basketball/research/boutique?${params}`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The boutique model rows could not be loaded. Please reload."); return r.json() as Promise<Result>; }).then(setResult).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [kind, season, selected, page, direction, query]);
  const reset = (fn: () => void) => { setPage(0); fn(); };
  return <>
    <div className="page-title"><div className="eyebrow">Publisher model archive / attributed SportsDataverse releases</div><h1>Bring more<br /><em>models to the table.</em></h1><p>Explore a second, source-attributed lens on team strength and player value. These ratings and Box Plus/Minus estimates are preserved as published; Silvermine forecasts and ratings remain independent.</p><div className="hero-actions"><Link className="button" href="/basketball/ratings/">Open Silvermine ratings ↗</Link><Link className="hero-link" href="/basketball/learn/">Learn the metrics →</Link></div></div>
    <div className="recruiting-views" aria-label="Boutique model view"><button aria-pressed={kind === "ratings"} onClick={() => { setKind("ratings"); setPage(0); }}>Team ratings</button><button aria-pressed={kind === "players"} onClick={() => { setKind("players"); setPage(0); }}>Player value</button></div>
    <div className="strip"><div><strong>{result?.total.toLocaleString() ?? "—"}</strong><span>{kind === "ratings" ? "Team records" : "Player/team records"}</span></div><div><strong>{result?.non_null.toLocaleString() ?? "—"}</strong><span>Records with this metric</span></div><div><strong>{metrics.length || "—"}</strong><span>Published metrics</span></div><div><strong>{seasons.length || "—"}</strong><span>Available seasons</span></div></div>
    <div className="toolbar"><label className="control"><span>SOURCE SEASON</span><select value={season} onChange={(e) => reset(() => setSeason(e.target.value))}>{!seasons.length && <option value={season}>{season}</option>}{seasons.map((s) => <option key={s} value={s}>{s - 1}–{String(s).slice(-2)}</option>)}</select></label><label className="control"><span>METRIC</span><select value={selected?.key || ""} onChange={(e) => reset(() => setMetric(e.target.value))}>{metrics.map((m) => <option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label className="control"><span>{kind === "ratings" ? "PROGRAM" : "PLAYER OR PROGRAM"}</span><input type="search" value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder={kind === "ratings" ? "Search programs" : "Search players or programs"} /></label><label className="control"><span>ORDER</span><select value={direction} onChange={(e) => reset(() => setDirection(e.target.value as "desc" | "asc"))}><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label></div>
    {selected && <p className="note" style={{ marginBottom: 20 }}><strong>{selected.label}</strong> · {selected.unit}. Source formulas and qualifications belong to the publisher release; no source value is fed into Silvermine's production forecast.</p>}
    {error ? <p role="alert" className="status-error">{error}</p> : !result ? <p role="status" className="empty">Loading boutique model rows…</p> : <><div className="section-heading" style={{ marginBottom: 20 }}><p>{result.total.toLocaleString()} matching records · page {page + 1} of {Math.max(1, Math.ceil(result.total / result.page_size))}</p><button className="button secondary" type="button" onClick={() => downloadCsv(`basketball-${kind}-${selected?.key}-${season}.csv`, toCsv(kind === "ratings" ? ["Publisher rank", "Program", "Source ID", result.metric.label] : ["Player", "Player ID", "Program", "Program ID", result.metric.label, "Box BPM"], result.rows.map((r) => kind === "ratings" ? [r.value, r.team, r.id, display(r.value, result.metric)] : [r.player, r.id, r.team, r.team_id, display(r.value, result.metric), r.bpm])))}>Download CSV ↓</button></div><div className="table-scroll"><table className="data-table"><thead><tr>{kind === "ratings" ? <><th>Publisher rank</th><th>Program</th><th>Source ID</th></> : <><th>Player</th><th>Program</th><th>Player ID</th></> }<th className="numeric">{result.metric.label}</th>{kind === "players" && <th className="numeric">Box BPM</th>}</tr></thead><tbody>{result.rows.map((r) => <tr key={`${r.id}-${r.team_id || ""}`}>
      {kind === "ratings" ? <><td className="rank-number">{display(r.value, result.metric)}</td><td><Link href={`/basketball/programs/${r.id}/`}>{r.team}</Link></td><td><small>{r.id}</small></td></> : <><td><Link href={`/basketball/player/?id=${r.id}&season=${season}`}>{r.player || r.id}</Link></td><td><Link href={`/basketball/programs/${r.team_id}/`}>{r.team}</Link></td><td><small>{r.id}</small></td></>}
      <td className="numeric"><strong>{display(r.value, result.metric)}</strong></td>{kind === "players" && <td className="numeric">{fmt(r.bpm, 1)}</td>}
    </tr>)}</tbody></table></div>{!result.rows.length && <p className="empty">No records match these filters.</p>}<div className="pagination"><span>{result.total.toLocaleString()} records · source identities remain attributable</span><div><button className="button secondary" disabled={!page} onClick={() => setPage(page - 1)}>← Previous</button><button className="button secondary" disabled={(page + 1) * result.page_size >= result.total} onClick={() => setPage(page + 1)}>Next →</button></div></div></>}
    <p className="note" style={{ marginTop: 24 }}>Source: SportsDataverse <a href="https://github.com/sportsdataverse/sportsdataverse-data/releases" target="_blank" rel="noreferrer">men&apos;s college basketball model releases ↗</a>. Ratings and player value are source-published estimates, not claims of eligibility, availability, future role or betting edge.</p>
  </>;
}
