"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { downloadCsv, toCsv } from "../../_lib/csv";
import { date, fmt } from "../../_lib/format";
import type { BBTeam } from "../../_lib/basketball-types";

type Kind = "ratings" | "players";
type Metric = { key: string; label: string; unit: string };
type SourceReceipt = { season: number; url: string; fetched_at: string; sha256: string };
type Row = { id: string; team: string; abbreviation?: string | null; player?: string | null; team_id?: string; value: number | null; bpm?: number | null; rank?: number | null; metric_rank?: number | null; publisher_rank?: number | null; ranked_count?: number | null };
type Result = { kind: Kind; season: number; metric: Metric; page: number; page_size: number; total: number; non_null: number; ranking?: { direction: "asc" | "desc"; population: string; ranked_count: number }; rows: Row[] };
function display(value: number | null, metric: Metric) { if (value == null) return "—"; return metric.unit === "rank" ? fmt(value, 0) : fmt(value, 1); }
function deltaDisplay(publisherRank: number | null, independentRank: number | null) {
  if (publisherRank == null || independentRank == null) return "—";
  const delta = publisherRank - independentRank;
  return delta === 0 ? "0" : `${delta > 0 ? "+" : "−"}${Math.abs(delta)}`;
}
export default function Boutique({ ratings }: { ratings: BBTeam[] }) {
  const params = useSearchParams();
  const initialKind = params.get("kind") === "players" ? "players" : "ratings";
  const initialSeason = /^\d{4}$/.test(params.get("season") || "") ? params.get("season")! : "2026";
  const initialMetric = /^[a-z_]{2,20}$/.test(params.get("metric") || "") ? params.get("metric")! : initialKind === "ratings" ? "rank" : "box_bpm";
  const [kind, setKind] = useState<Kind>(initialKind), [seasons, setSeasons] = useState<number[]>([]), [metrics, setMetrics] = useState<Metric[]>([]), [sourceReceipts, setSourceReceipts] = useState<SourceReceipt[]>([]);
  const [season, setSeason] = useState(initialSeason), [metric, setMetric] = useState(initialMetric), [query, setQuery] = useState(params.get("q") || ""), [direction, setDirection] = useState<"desc" | "asc">(params.get("direction") === "desc" ? "desc" : "asc"), [page, setPage] = useState(0);
  const [result, setResult] = useState<Result | null>(null), [error, setError] = useState(""), [retryNonce, setRetryNonce] = useState(0);
  const independentRatings = useMemo(() => new Map(ratings.map((rating) => [rating.id, rating])), [ratings]);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/basketball/research/boutique?kind=${kind}&meta=1`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The boutique model catalog is unavailable."); return r.json() as Promise<{ seasons: number[]; metrics: Metric[]; source_receipts?: SourceReceipt[] }>; }).then((p) => { setSeasons(p.seasons); setMetrics(p.metrics); setSourceReceipts(p.source_receipts || []); if (!p.metrics.some((candidate) => candidate.key === metric)) setMetric(p.metrics[0]?.key || ""); if (p.seasons.length && !p.seasons.includes(Number(season))) setSeason(String(p.seasons[0])); }).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [kind, metric, retryNonce, season]);
  const selected = useMemo(() => metrics.find((m) => m.key === metric) || metrics[0] || null, [metrics, metric]);
  const sourceReceipt = sourceReceipts.find((receipt) => receipt.season === Number(season));
  useEffect(() => { if (!selected) return; const controller = new AbortController(); setResult(null); setError(""); const params = new URLSearchParams({ kind, season, metric: selected.key, page: String(page), direction }); if (query.trim()) params.set("q", query.trim()); fetch(`/api/basketball/research/boutique?${params}`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The boutique model rows could not be loaded. Please reload."); return r.json() as Promise<Result>; }).then(setResult).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [direction, kind, page, query, retryNonce, season, selected]);
  const retryArchive = () => { setError(""); setRetryNonce((value) => value + 1); };
  const reset = (fn: () => void) => { setPage(0); fn(); };
  return <>
    <div className="page-title"><div className="eyebrow">Additional model archive</div><h1>Bring more<br /><em>models to the table.</em></h1><p>Explore an additional lens on team strength and player value. These ratings and Box Plus/Minus estimates are preserved as recorded; Silvermine forecasts and ratings remain independent.</p><div className="hero-actions"><Link className="button" href="/basketball/ratings/">Open Silvermine ratings ↗</Link><Link className="hero-link" href="/basketball/learn/">Learn the metrics →</Link></div></div>
    <div className="recruiting-views" aria-label="Boutique model view"><button aria-pressed={kind === "ratings"} onClick={() => { setKind("ratings"); setPage(0); }}>Team ratings</button><button aria-pressed={kind === "players"} onClick={() => { setKind("players"); setPage(0); }}>Player value</button></div>
    <div className="model-compare-grid">
      <article className="paper-panel"><div className="eyebrow">Independent comparison</div><h2>Read disagreement as a question.</h2><p>For current team rows, the recorded reference rank stays separate from the selected metric and its national standing. A positive delta means the recorded overall rank is lower than Silvermine&apos;s rank; it is a prompt to inspect schedule, style and personnel, not a pick.</p></article>
      <article className="paper-panel"><div className="eyebrow">Model boundary</div><h2>Keep comparison models separate.</h2><p>Comparison values are kept separate from the independent Silvermine model and are shown only as contextual reference.</p></article>
    </div>
    <div className="strip"><div><strong>{result?.total.toLocaleString() ?? "—"}</strong><span>{kind === "ratings" ? "Team records" : "Player/team records"}</span></div><div><strong>{result?.non_null.toLocaleString() ?? "—"}</strong><span>Records with this metric</span></div><div><strong>{metrics.length || "—"}</strong><span>Metrics</span></div><div><strong>{seasons.length || "—"}</strong><span>Available seasons</span></div></div>
    <div className="toolbar"><label className="control"><span>SEASON</span><select value={season} onChange={(e) => reset(() => setSeason(e.target.value))}>{!seasons.length && <option value={season}>{season}</option>}{seasons.map((s) => <option key={s} value={s}>{s - 1}–{String(s).slice(-2)}</option>)}</select></label><label className="control"><span>METRIC</span><select value={selected?.key || ""} onChange={(e) => reset(() => setMetric(e.target.value))}>{metrics.map((m) => <option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label className="control"><span>{kind === "ratings" ? "PROGRAM" : "PLAYER OR PROGRAM"}</span><input type="search" value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder={kind === "ratings" ? "Search programs" : "Search players or programs"} /></label><label className="control"><span>ORDER</span><select value={direction} onChange={(e) => reset(() => setDirection(e.target.value as "desc" | "asc"))}><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label></div>
    {selected && <p className="note" style={{ marginBottom: 20 }}><strong>{selected.label}</strong> · {selected.unit}. Reference formulas and qualifications stay separate; no comparison value is fed into Silvermine&apos;s production forecast. {sourceReceipt ? <>Receipt fetched {date(sourceReceipt.fetched_at)} · SHA-256 {sourceReceipt.sha256.slice(0, 16)}… · Retained</> : "Capture receipt unavailable for this edition."}</p>}
    {error ? <div role="alert" className="status-error"><span>{error}</span><button className="button secondary" type="button" onClick={retryArchive}>Retry boutique archive</button></div> : !result ? <p role="status" className="empty">Loading boutique model rows…</p> : <><div className="section-heading" style={{ marginBottom: 20 }}><p>{result.total.toLocaleString()} matching records · page {page + 1} of {Math.max(1, Math.ceil(result.total / result.page_size))}</p><button className="button secondary" type="button" onClick={() => downloadCsv(`basketball-${kind}-${selected?.key}-${season}.csv`, toCsv(kind === "ratings" ? ["Metric rank", "Ranked cohort", "Program", "Team ID", result.metric.label, "Recorded overall rank", "Silvermine rank", "Overall rank delta", "Silvermine adjusted net"] : ["Player rank", "Ranked cohort", "Player", "Player ID", "Program", "Program ID", result.metric.label, "Box BPM"], result.rows.map((r) => { const independent = kind === "ratings" ? independentRatings.get(r.id) : null; return kind === "ratings" ? [r.metric_rank, r.ranked_count ?? result.ranking?.ranked_count, r.team, r.id, display(r.value, result.metric), r.publisher_rank, independent?.rank, deltaDisplay(r.publisher_rank ?? null, independent?.rank ?? null), independent?.adj_net] : [r.rank, r.ranked_count ?? result.ranking?.ranked_count, r.player, r.id, r.team, r.team_id, display(r.value, result.metric), r.bpm]; })))}>Download CSV ↓</button></div><p className="note">Metric rank uses all teams with a recorded value in this season and follows the selected highest-first or lowest-first order. The recorded overall reference rank remains separate. When a team ID matches the current Silvermine edition, the overall rank delta and adjusted net show model disagreement; an em dash means no audited crosswalk in this edition.</p><div className="table-scroll"><table className="data-table"><thead><tr>{kind === "ratings" ? <><th>Metric rank</th><th>Program</th><th>Team ID</th></> : <><th>Player rank</th><th>Player</th><th>Program</th><th>Player ID</th></> }<th className="numeric">{result.metric.label}</th>{kind === "ratings" && <><th className="numeric">Recorded overall</th><th className="numeric">Silvermine rank</th><th className="numeric">Overall delta</th><th className="numeric">Silvermine net</th></>}{kind === "players" && <><th className="numeric">Box BPM</th><th className="numeric">Ranked cohort</th></>}</tr></thead><tbody>{result.rows.map((r) => { const independent = kind === "ratings" ? independentRatings.get(r.id) : null; return <tr key={`${r.id}-${r.team_id || ""}`}>
      {kind === "ratings" ? <><td className="rank-number">{r.metric_rank ?? "—"}<small>{r.ranked_count ?? result.ranking?.ranked_count ?? 0} teams with a recorded value</small></td><td><Link href={`/basketball/programs/${r.id}/`}>{r.team}</Link></td><td><small>{r.id}</small></td></> : <><td className="rank-number">{r.rank ?? "—"}<small>{r.ranked_count ?? result.ranking?.ranked_count ?? 0} players with a recorded value</small></td><td><Link href={`/basketball/player/?id=${r.id}&season=${season}`}>{r.player || r.id}</Link></td><td><Link href={`/basketball/programs/${r.team_id}/`}>{r.team}</Link></td><td><small>{r.id}</small></td></>}
      <td className="numeric"><strong>{display(r.value, result.metric)}</strong></td>{kind === "ratings" && <><td className="numeric">{r.publisher_rank ?? "—"}</td><td className="numeric">{independent?.rank ?? "—"}</td><td className="numeric rank-delta">{deltaDisplay(r.publisher_rank ?? null, independent?.rank ?? null)}</td><td className="numeric">{independent?.adj_net == null ? "—" : fmt(independent.adj_net, 1)}</td></>}{kind === "players" && <><td className="numeric">{fmt(r.bpm, 1)}</td><td className="numeric">{r.ranked_count ?? result.ranking?.ranked_count ?? "—"}</td></>}
    </tr>; })}</tbody></table></div>{!result.rows.length && <p className="empty">No records match these filters.</p>}<div className="pagination"><span>{result.total.toLocaleString()} records · record identities remain available</span><div><button className="button secondary" disabled={!page} onClick={() => setPage(page - 1)}>← Previous</button><button className="button secondary" disabled={(page + 1) * result.page_size >= result.total} onClick={() => setPage(page + 1)}>Next →</button></div></div></>}
  </>;
}
