import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";

type Bindings = Env;
type RecordValue = Record<string, unknown>;
type Division = "fcs" | "d2" | "d3";

const DIVISIONS: readonly Division[] = ["fcs", "d2", "d3"];
const ASSET_TIMEOUT_MS = 2500;
const CACHE_TTL = 300;

const querySchema = z.object({
  season: z.coerce.number().int().min(2022).max(2035).default(2026),
  division: z.enum(["all", "fcs", "d2", "d3"]).default("all"),
  // Keep a direct matchup lookup available for lower-division game pages.
  gameId: z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/).optional(),
  status: z.enum(["all", "upcoming", "completed"]).default("upcoming"),
  q: z.string().trim().max(120).optional(),
  model: z.union([
    z.literal("latest"),
    z.literal("all"),
    z.string().trim().regex(/^[A-Za-z0-9._-]{1,120}$/),
  ]).default("latest"),
  page: z.coerce.number().int().min(0).max(1000).default(0),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  meta: z.enum(["0", "1"]).default("0"),
});

function withTimeout<T>(promise: Promise<T>, milliseconds: number): Promise<T> {
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error("football lower forecast asset timed out")), milliseconds);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

function isRecord(value: unknown): value is RecordValue {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function finite(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function nonNegativeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0;
}

function isHttps(value: unknown): value is string {
  if (typeof value !== "string" || !value.startsWith("https://")) return false;
  try { return new URL(value).protocol === "https:"; } catch { return false; }
}

function validSha256(value: unknown): value is string {
  return typeof value === "string" && /^[a-f0-9]{64}$/i.test(value);
}

function validPrediction(value: unknown): value is RecordValue {
  if (!isRecord(value)) return false;
  const required = ["home_margin", "total", "home_score", "away_score", "home_win_probability", "margin_low", "margin_high"];
  if (required.some((field) => !finite(value[field]))) return false;
  const total = value.total as number;
  const homeScore = value.home_score as number;
  const awayScore = value.away_score as number;
  const homeMargin = value.home_margin as number;
  const homeWinProbability = value.home_win_probability as number;
  const marginLow = value.margin_low as number;
  const marginHigh = value.margin_high as number;
  if (total < 0 || homeWinProbability < 0 || homeWinProbability > 1) return false;
  if (marginLow > marginHigh) return false;
  // The publisher rounds scores to one decimal and margins/totals to two;
  // this tolerance catches stale or hand-edited rows without rejecting valid
  // rounding residue.
  if (Math.abs(homeScore + awayScore - total) > 0.21) return false;
  if (Math.abs(homeScore - awayScore - homeMargin) > 0.21) return false;
  return true;
}

function validForecast(value: unknown, division: Division, modelId: string): value is RecordValue {
  return isRecord(value)
    && typeof value.game_id === "string" && value.game_id.length > 0
    && typeof value.kickoff === "string" && !Number.isNaN(Date.parse(value.kickoff))
    && typeof value.home_id === "string" && value.home_id.length > 0
    && typeof value.away_id === "string" && value.away_id.length > 0
    && typeof value.home_name === "string" && value.home_name.length > 0
    && typeof value.away_name === "string" && value.away_name.length > 0
    && value.scope_division === division
    && value.model_id === modelId
    && validPrediction(value.prediction);
}

function validModel(value: unknown, division: Division, season: number): value is RecordValue & { id: string } {
  if (!isRecord(value)
    || typeof value.id !== "string" || value.id.length === 0
    || typeof value.version !== "string"
    || value.division !== division
    || value.target_season !== season
    || !nonNegativeInteger(value.training_games) || value.training_games < 100
    || !Array.isArray(value.training_seasons) || value.training_seasons.length < 3
    || !nonNegativeInteger(value.calibration_season)
    || !isRecord(value.calibration)
    || !finite(value.calibration.margin_half_width) || value.calibration.margin_half_width < 0
    || !Array.isArray(value.ratings)
    || !Array.isArray(value.limitations)) return false;
  return true;
}

/**
 * Validate the complete lower-division artifact before exposing any rows.
 * The artifact is generated by the football publisher and contains one
 * independently fitted model for each exact division. A partial or malformed
 * release must never look like a trustworthy forecast response.
 */
export function parseFootballLowerForecastArtifact(value: unknown, season: number): {
  artifact: RecordValue;
  forecasts: Record<Division, RecordValue[]>;
  models: Record<Division, RecordValue>;
} | null {
  if (!isRecord(value)
    || value.schema_version !== 2
    || value.sport !== "football"
    || value.season !== season
    || typeof value.generated_at !== "string"
    || Number.isNaN(Date.parse(value.generated_at))
    || !isRecord(value.coverage)
    || !isRecord(value.models)
    || !isRecord(value.forecasts)
    || !isRecord(value.source)
    || value.source.dataset !== "schedule"
    || value.source.season !== season
    || !isHttps(value.source.url)
    || typeof value.source.fetched_at !== "string"
    || Number.isNaN(Date.parse(value.source.fetched_at))
    || !validSha256(value.source.sha256)) return null;

  const models = {} as Record<Division, RecordValue>;
  const forecasts = {} as Record<Division, RecordValue[]>;
  for (const division of DIVISIONS) {
    if (!validModel(value.models[division], division, season)) return null;
    const model = value.models[division] as RecordValue & { id: string };
    const rows = value.forecasts[division];
    if (!Array.isArray(rows) || rows.some((row) => !validForecast(row, division, model.id))) return null;
    const ids = new Set(rows.map((row) => String((row as RecordValue).game_id)));
    if (ids.size !== rows.length) return null;
    const coverage = value.coverage[division];
    if (!isRecord(coverage)
      || !nonNegativeInteger(coverage.forecast_games)
      || coverage.forecast_games !== rows.length
      || !nonNegativeInteger(coverage.upcoming_games)
      || coverage.forecast_games > coverage.upcoming_games) return null;
    models[division] = model;
    forecasts[division] = rows as RecordValue[];
  }
  return { artifact: value, forecasts, models };
}

function edgeCache() {
  return typeof caches === "undefined" ? null : (caches as unknown as { default: Cache }).default;
}

function publicModel(model: RecordValue, forecastRows: number) {
  return {
    model_id: model.id,
    version: model.version,
    division: model.division,
    target_season: model.target_season,
    cutoff: model.cutoff,
    training_seasons: model.training_seasons,
    training_games: model.training_games,
    calibration_season: model.calibration_season,
    calibration: model.calibration,
    forecast_rows: forecastRows,
    ratings_rows: Array.isArray(model.ratings) ? model.ratings.length : 0,
    limitations: model.limitations,
  };
}

export const footballLowerForecasts = new Hono<{ Bindings: Bindings }>();
footballLowerForecasts.get("/", zValidator("query", querySchema), async (c) => {
  const args = c.req.valid("query");
  if (!c.env.ASSETS) return c.json({ error: "The football lower-division forecast release is unavailable.", code: "release_unavailable" }, 503, { "Cache-Control": "no-store" });
  const assetPath = `/data/football/lower-division-results-${args.season}.json`;
  const cache = edgeCache();
  const cacheKey = new Request(c.req.url, { method: "GET" });
  if (cache) {
    try {
      const cached = await withTimeout(cache.match(cacheKey), 1000);
      if (cached) return cached;
    } catch { /* Cache failures must not hide the source release. */ }
  }
  try {
    const asset = await withTimeout(c.env.ASSETS.fetch(new Request(new URL(assetPath, c.req.url))), ASSET_TIMEOUT_MS);
    if (!asset.ok) return c.json({ error: "The football lower-division forecast release is unavailable.", code: "release_unavailable", season: args.season }, 503, { "Cache-Control": "no-store" });
    const parsed = parseFootballLowerForecastArtifact(await asset.json(), args.season);
    if (!parsed) return c.json({ error: "The football lower-division forecast release failed integrity validation.", code: "release_integrity_failed" }, 503, { "Cache-Control": "no-store" });

    const selectedDivisions = args.division === "all" ? DIVISIONS : [args.division];
    const selectedRows = selectedDivisions.flatMap((division) => parsed.forecasts[division].map((row) => ({ ...row, division }))) as Array<RecordValue & { division: Division }>;
    const modelFiltered = args.model === "latest" || args.model === "all"
      ? selectedRows
      : selectedRows.filter((row) => row.model_id === args.model);
    const gameFiltered = args.gameId
      ? modelFiltered.filter((row) => row.game_id === args.gameId)
      : modelFiltered;
    const needle = args.q?.toLocaleLowerCase();
    const filtered = needle
      ? gameFiltered.filter((row) => `${row.home_name} ${row.away_name}`.toLocaleLowerCase().includes(needle))
      : gameFiltered;
    filtered.sort((a, b) => String(a.kickoff).localeCompare(String(b.kickoff)) || String(a.game_id).localeCompare(String(b.game_id)));
    const response = args.meta === "1"
      ? c.json({
        season: args.season,
        source: parsed.artifact.source,
        generated_at: parsed.artifact.generated_at,
        available_divisions: [...DIVISIONS],
        coverage: Object.fromEntries(DIVISIONS.map((division) => [division, (parsed.artifact.coverage as RecordValue)[division]])),
        models: Object.fromEntries(DIVISIONS.map((division) => [division, publicModel(parsed.models[division], parsed.forecasts[division].length)])),
        integrity: { divisions: DIVISIONS.length, forecast_rows: selectedRows.length, valid_rows: selectedRows.length },
      })
      : (() => {
        const start = args.page * args.limit;
        const rows = filtered.slice(start, start + args.limit);
        return c.json({
          season: args.season,
          division: args.division,
          status: args.status,
          model: args.model,
          page: args.page,
          page_size: args.limit,
          total: args.status === "completed" ? 0 : filtered.length,
          pages: args.status === "completed" ? 1 : Math.max(1, Math.ceil(filtered.length / args.limit)),
          source: "published_asset",
          generated_at: parsed.artifact.generated_at,
          models: Object.fromEntries(selectedDivisions.map((division) => [division, publicModel(parsed.models[division], parsed.forecasts[division].length)])),
          rows: args.status === "completed" ? [] : rows,
        });
      })();
    response.headers.set("Cache-Control", `public, max-age=${CACHE_TTL}`);
    if (cache) c.executionCtx.waitUntil(cache.put(cacheKey, response.clone()).catch(() => undefined));
    return response;
  } catch {
    return c.json({ error: "The football lower-division forecast release is temporarily unavailable.", code: "release_unavailable" }, 503, { "Cache-Control": "no-store" });
  }
});
