import { getBasketball } from "./_lib/basketball-data";
import { getScoutIndex } from "./_lib/scouting-data";
import type { MetadataRoute } from "next";
import { getOverview } from "./_lib/data";
export const dynamic = "force-static";
export default function sitemap(): MetadataRoute.Sitemap {
  const d = getOverview(),
    basketball = getBasketball(),
    base = "https://bball.silvermine.dev";
  return [
    "",
    "/football/",
    "/research/scorecard/",
    "/research/markets/",
    "/research/briefs/",
    "/research/coverage/",
    "/basketball/",
    "/basketball/learn/",
    "/basketball/ratings/",
    "/basketball/rankings/",
    "/basketball/boutique/",
    "/basketball/lineups/",
    "/basketball/conferences/",
    "/basketball/standings/",
    "/basketball/programs/",
    "/basketball/compare/",
    "/basketball/shooting/",
    "/basketball/pbp/",
    "/basketball/possession-style/",
    ...getScoutIndex().teams.map((t) => `/basketball/programs/${t.id}/`),
    "/basketball/players/",
    "/basketball/player-profiles/",
    "/basketball/ncaa-player-box/",
    "/basketball/ncaa-compare/",
    "/basketball/ncaa-rankings/",
    "/basketball/ncaa-careers/",
    "/basketball/ncaa-rosters/",
    "/basketball/ncaa-high-schools/",
    "/basketball/ncaa-shooting/",
    "/basketball/source-stats/",
    "/basketball/team-stats/",
    "/basketball/leaders/",
    "/basketball/ncaa/",
    "/basketball/compare-players/",
    "/basketball/scouting-board/",
    "/basketball/recruiting/",
    "/basketball/recruiting/fit/",
    "/basketball/roster-lab/",
    "/basketball/roster-board/",
    "/basketball/impact/",
    "/basketball/model/",
    "/basketball/evaluation/",
    "/basketball/matchups/",
    "/basketball/briefs/",
    "/basketball/forecast-lab/",
    "/basketball/pressroom/",
    "/basketball/news/",
    "/basketball/gameplan/",
    "/basketball/film/",
    "/basketball/season/",
    ...basketball
      .upcoming.filter((g) => g.prediction || g.fallback_prediction)
      .map((g) => `/basketball/briefs/${g.id}/`),
    "/football/matchups/",
    "/football/players/",
    "/football/source-stats/",
    "/football/careers/",
    "/football/events/",
    "/football/efficiency/",
    "/football/ratings/",
    "/football/methodology/",
    "/football/evaluation/",
    "/football/features/",
    "/football/learn/",
    "/blog/",
    "/conferences/",
    "/film/",
    "/blog/reading-the-forecast/",
    "/blog/understanding-player-epa/",
    "/blog/market-comparison/",
    "/blog/basketball-four-factors/",
    "/blog/basketball-impact/",
    "/blog/basketball-recruiting-workload/",
    "/blog/basketball-player-rates/",
    "/blog/basketball-recruiting-fit/",
    "/blog/basketball-ranking-playbook/",
    "/blog/basketball-possession-style/",
    "/blog/basketball-availability-evidence/",
    "/blog/basketball-player-game-logs/",
    "/blog/basketball-roster-transitions/",
    ...d.upcoming.filter((g) => g.prediction).map((g) => `/blog/game-${g.id}/`),
    ...basketball
      .upcoming.filter((g) => g.prediction || g.fallback_prediction)
      .map((g) => `/blog/basketball-game-${g.id}/`),
  ].map((path) => ({
    url: base + path,
    lastModified:
      path.endsWith("/evaluation/") || path === "/football/features/"
        ? undefined
        : path.startsWith("/basketball/") || path.startsWith("/blog/basketball-")
          ? basketball.generated_at
          : d.generated_at,
    changeFrequency: path.startsWith("/blog/") ? "weekly" : "daily",
  }));
}
