"use client";
import { useEffect, useMemo, useState } from "react";
import { downloadCsv, toCsv } from "../../_lib/csv";
import { fmt } from "../../_lib/format";
import { lineupFilterSearch, parseLineupFilters, type LineupDirection } from "../../_lib/lineups";
type Metric = { key: string; label: string; unit: string };
type Row = { id: string; team: string; players: (string | null)[]; value: number | null; stats: Record<string, number | null> };
type Result = { season: number; metric: Metric; min_poss: number; page: number; page_size: number; total: number; non_null: number; rows: Row[] };
const shown = (value: number | null, metric: Metric) => value == null ? "—" : fmt(value, metric.key === "games" ? 0 : 1);
export default function Lineups() {
  const initial = typeof window === "undefined" ? parseLineupFilters("") : parseLineupFilters(window.location.search);
  const [metrics, setMetrics] = useState<Metric[]>([]), [seasons, setSeasons] = useState<number[]>([2026, 2025]), [season, setSeason] = useState(String(initial.season)), [metric, setMetric] = useState(initial.metric), [minPoss, setMinPoss] = useState(initial.minPoss), [query, setQuery] = useState(initial.query), [direction, setDirection] = useState<LineupDirection>(initial.direction), [page, setPage] = useState(initial.page), [result, setResult] = useState<Result | null>(null), [error, setError] = useState(""), [copied, setCopied] = useState("");
  const selected = useMemo(() => metrics.find((m) => m.key === metric) || null, [metrics, metric]);
  useEffect(() => { const next = lineupFilterSearch({ season: Number(season), metric, minPoss, direction, query, page }); if (next !== window.location.search) window.history.replaceState(window.history.state, "", `${window.location.pathname}${next}${window.location.hash}`); }, [direction, metric, minPoss, page, query, season]);
  useEffect(() => { const controller = new AbortController(); fetch("/api/basketball/research/lineups?meta=1", { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The lineup catalog is unavailable."); return r.json() as Promise<{ seasons: number[]; metrics: Metric[] }>; }).then((p) => { setSeasons(p.seasons); setMetrics(p.metrics); setMetric((current) => p.metrics.some((item) => item.key === current) ? current : (p.metrics[0]?.key || "net_per_100")); if (!p.seasons.includes(Number(season))) setSeason(String(p.seasons[0] || 2026)); }).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, []);
  useEffect(() => { if (!selected) return; const controller = new AbortController(); setResult(null); setError(""); const params = new URLSearchParams({ season, metric: selected.key, minPoss, direction, page: String(page) }); if (query.trim()) params.set("q", query.trim()); fetch(`/api/basketball/research/lineups?${params}`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error("The lineup rows could not be loaded. Please reload."); return r.json() as Promise<Result>; }).then(setResult).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [season, selected, minPoss, direction, page, query]);
  const reset = (fn: () => void) => { setPage(0); fn(); };
  const share = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied("Lineup link copied."); } catch { setCopied("Copy the filtered URL from your address bar."); } };
  return <>
    <div className="page-title"><div className="eyebrow">NCAA source archive / five-player combinations</div><h1>Find the<br /><em>right five.</em></h1><p>Read lineup combinations through possessions, scoring and opponent results. The archive aggregates source stints by lineup key, making the sample size visible before a coach draws a conclusion.</p></div>
    <div className="strip"><div><strong>{result?.total.toLocaleString() ?? "—"}</strong><span>Lineups in view</span></div><div><strong>{result?.non_null.toLocaleString() ?? "—"}</strong><span>With selected metric</span></div><div><strong>{seasons.length || "—"}</strong><span>Available seasons</span></div><div><strong>{result?.min_poss ?? "—"}</strong><span>Minimum possessions</span></div></div>
    <div className="toolbar"><label className="control"><span>SEASON</span><select value={season} onChange={(e) => reset(() => setSeason(e.target.value))}>{seasons.map((value) => <option key={value} value={value}>{value - 1}–{String(value).slice(-2)}</option>)}</select></label><label className="control"><span>METRIC</span><select value={selected?.key || ""} onChange={(e) => reset(() => setMetric(e.target.value))}>{metrics.map((m) => <option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label className="control"><span>MINIMUM POSSESSIONS</span><select value={minPoss} onChange={(e) => reset(() => setMinPoss(e.target.value))}><option value="0">All samples</option><option value="20">20+</option><option value="40">40+</option><option value="100">100+</option><option value="200">200+</option></select></label><label className="control"><span>TEAM OR PLAYER</span><input type="search" value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder="Search names or teams" /></label><label className="control"><span>ORDER</span><select value={direction} onChange={(e) => reset(() => setDirection(e.target.value as LineupDirection))}><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label><button className="button secondary" type="button" onClick={share}>Copy lineup link</button></div>
    {copied && <p role="status">{copied}</p>}
    {selected && <p className="note" style={{ marginBottom: 20 }}><strong>{selected.label}</strong> · {selected.unit}. Net rating is 100 × (points/possessions − opponent points/opponent possessions); it is a descriptive source-derived rate, not a forecast.</p>}
    {error ? <p role="alert" className="status-error">{error}</p> : !result ? <p role="status" className="empty">Loading lineup rows…</p> : <><div className="section-heading" style={{ marginBottom: 20 }}><p>{result.total.toLocaleString()} matching lineups · page {page + 1} of {Math.max(1, Math.ceil(result.total / result.page_size))}</p><button className="button secondary" type="button" onClick={() => downloadCsv(`basketball-lineups-${season}.csv`, toCsv(["Team", "Players", "Lineup ID", result.metric.label, "Possessions", "Games", "Offensive rating", "Defensive rating"], result.rows.map((r) => [r.team, r.players.filter(Boolean).join(" / "), r.id, shown(r.value, result.metric), r.stats.poss, r.stats.games, r.stats.off_rtg, r.stats.def_rtg])))}>Download CSV ↓</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Team</th><th>Five-player lineup</th><th>Lineup ID</th><th className="numeric">{result.metric.label}</th><th className="numeric">Poss.</th><th className="numeric">Games</th><th className="numeric">Off. rtg</th><th className="numeric">Def. rtg</th></tr></thead><tbody>{result.rows.map((r) => <tr key={r.id}><td>{r.team}</td><td><strong>{r.players.filter(Boolean).join(" · ")}</strong></td><td><small>{r.id}</small></td><td className="numeric">{shown(r.value, result.metric)}</td><td className="numeric">{fmt(r.stats.poss, 0)}</td><td className="numeric">{fmt(r.stats.games, 0)}</td><td className="numeric">{fmt(r.stats.off_rtg, 1)}</td><td className="numeric">{fmt(r.stats.def_rtg, 1)}</td></tr>)}</tbody></table></div>{!result.rows.length && <p className="empty">No lineups match these filters.</p>}<div className="pagination"><span>{result.total.toLocaleString()} source-derived lineup aggregates · sample size shown</span><div><button className="button secondary" disabled={!page} onClick={() => setPage(page - 1)}>← Previous</button><button className="button secondary" disabled={(page + 1) * result.page_size >= result.total} onClick={() => setPage(page + 1)}>Next →</button></div></div></>}
    <p className="note" style={{ marginTop: 24 }}>Source: NCAA-derived lineup release via SportsDataverse. Player names in this product are source-native lineup labels and are not joined to ESPN player IDs. Low-possession combinations can be unstable; use the threshold and games columns.</p>
  </>;
}
