export type BBPrediction = {
  home_score: number;
  away_score: number;
  home_margin: number;
  total: number;
  pace: number;
  home_win_probability: number;
  margin_low: number;
  margin_high: number;
};
export type BBGame = {
  id: string;
  season: number;
  starts_at: string;
  home_id: string;
  away_id: string;
  home_name: string;
  away_name: string;
  neutral: number;
  time_tbd: number;
  venue: string;
  broadcast: string;
  prediction: BBPrediction | null;
};
export type BBTeam = {
  id: string;
  name: string;
  rank: number;
  adj_off: number;
  adj_def: number;
  adj_net: number;
  adj_tempo: number;
  games: number;
  wins: number;
  sos: number | null;
  sos_games: number;
  efg: number | null;
  tov_rate: number | null;
  orb_rate: number | null;
  ft_rate: number | null;
  three_rate: number | null;
};
export type BBOverview = {
  season: number;
  label: string;
  generated_at: string;
  coverage: {
    schedule_records: number;
    completed_games: number;
    paired_box_games: number;
    unusable_completed_games: number;
    player_box_rows: number;
    unresolved_rows: number;
    upcoming_games: number;
    forecast_games: number;
  };
  ratings: BBTeam[];
  upcoming: BBGame[];
  model: {
    id: string;
    version: string;
    cutoff: string;
    training_games: number;
    training_seasons: number[];
    calibration: {
      season: number;
      games: number;
      logistic_coefficients: number[];
      margin_half_width: number;
    };
    evaluation: {
      season: number;
      games: number;
      unscored_games: number;
      margin_mae: number;
      margin_rmse: number;
      total_mae: number;
      winner_accuracy: number;
      brier: number;
      log_loss: number;
      interval_coverage: number;
      baseline_margin_mae: number;
      training_seasons: number[];
    };
    limitations: string[];
  };
  sources: {
    dataset: string;
    season: number;
    url: string;
    fetched_at: string;
    sha256: string;
  }[];
};
export type BBPlayer = {
  id: string;
  team_id: string;
  name: string;
  team: string;
  position: string | null;
  season: number;
  games: number;
  minutes: number;
  mpg: number;
  ppg: number | null;
  rpg: number | null;
  apg: number | null;
  spg: number | null;
  bpg: number | null;
  topg: number | null;
  efg: number | null;
  ts: number | null;
  three_pct: number | null;
  qualified: boolean;
  incomplete_box_games: number;
};
export type BBRoster = {
  id: string;
  name: string;
  team_id: string;
  team: string;
  previous_teams: string[];
  status: string;
  position: string | null;
  class_year: string | null;
  height: string | null;
  weight: string | null;
  source_url: string | null;
};
export type BBRosters = {
  season: number;
  previous_season: number;
  teams_observed: number;
  players_observed: number;
  prior_players_not_observed: number;
  status_counts: Record<string, number>;
  players: BBRoster[];
};
export type BBImpact = {
  player_id: string;
  person_id: string;
  player: string;
  team: string;
  orapm: number | null;
  drapm: number | null;
  rapm_net: number | null;
  off_poss: number | null;
  def_poss: number | null;
  qualified: boolean;
  rank: number | null;
};
