export type BBPrediction = {
  home_score: number;
  away_score: number;
  home_margin: number;
  total: number;
  pace: number;
  home_win_probability: number;
  margin_low: number;
  margin_high: number;
  estimate_type?: "cold_start";
  unknown_teams?: string[];
  margin_half_width?: number;
};
export type BBGame = {
  id: string;
  season: number;
  starts_at: string;
  home_id: string;
  away_id: string;
  home_name: string;
  away_name: string;
  neutral: number;
  time_tbd: number;
  venue: string;
  broadcast: string;
  prediction: BBPrediction | null;
  fallback_prediction?: BBPrediction | null;
};
export type BBTeam = {
  id: string;
  name: string;
  rank: number;
  adj_off: number;
  adj_def: number;
  adj_net: number;
  adj_tempo: number;
  games: number;
  wins: number;
  expected_wins: number | null;
  luck: number | null;
  luck_games: number;
  sos: number | null;
  sos_games: number;
  efg: number | null;
  tov_rate: number | null;
  orb_rate: number | null;
  ft_rate: number | null;
  three_rate: number | null;
  adj_off_efg?: number | null;
  adj_def_efg?: number | null;
  adj_off_tov?: number | null;
  adj_def_tov?: number | null;
  adj_off_orb?: number | null;
  adj_def_orb?: number | null;
  adj_off_ftr?: number | null;
  adj_def_ftr?: number | null;
};
export type BBOverview = {
  season: number;
  label: string;
  generated_at: string;
  coverage: {
    schedule_records: number;
    completed_games: number;
    paired_box_games: number;
    unusable_completed_games: number;
    player_box_rows: number;
    unresolved_rows: number;
    upcoming_games: number;
    forecast_games: number;
    baseline_estimate_games?: number;
  };
  ratings: BBTeam[];
  upcoming: BBGame[];
  model: {
    teams: string[];
    efficiency: number[];
    tempo: number[];
    id: string;
    version: string;
    cutoff: string;
    training_games: number;
    training_seasons: number[];
    calibration: {
      season: number;
      games: number;
      logistic_coefficients: number[];
      margin_half_width: number;
      fallback_margin_half_width?: number;
      fallback_games?: number;
    };
    evaluation: {
      season: number;
      games: number;
      unscored_games: number;
      margin_mae: number;
      margin_rmse: number;
      total_mae: number;
      winner_accuracy: number;
      brier: number;
      log_loss: number;
      interval_coverage: number;
      baseline_margin_mae: number;
      training_seasons: number[];
    };
    limitations: string[];
    fallback_priors?: Record<string, { off: number; def: number; tempo: number; games: number }>;
  };
  sources: {
    dataset: string;
    season: number;
    url: string;
    fetched_at: string;
    sha256: string;
  }[];
};
export type BBPlayer = {
  id: string;
  team_id: string;
  name: string;
  team: string;
  position: string | null;
  season: number;
  games: number;
  minutes: number;
  mpg: number;
  ppg: number | null;
  rpg: number | null;
  apg: number | null;
  spg: number | null;
  bpg: number | null;
  topg: number | null;
  efg: number | null;
  ts: number | null;
  three_pct: number | null;
  ft_rate: number | null;
  three_rate: number | null;
  tov_rate: number | null;
  qualified: boolean;
  incomplete_box_games: number;
};
export type BBRoster = {
  id: string;
  name: string;
  team_id: string;
  team: string;
  previous_teams: string[];
  status: string;
  position: string | null;
  class_year: string | null;
  height: string | null;
  weight: string | null;
  source_url: string | null;
  prior_production?: {
    games: number;
    minutes: number;
    mpg: number | null;
    ppg: number | null;
    rpg: number | null;
    apg: number | null;
    spg?: number | null;
    bpg?: number | null;
    topg?: number | null;
    efg?: number | null;
    ts?: number | null;
    three_pct?: number | null;
    ft_rate?: number | null;
    three_rate?: number | null;
    tov_rate?: number | null;
    qualified?: boolean;
    teams: string[];
  } | null;
};
export type BBRosters = {
  season: number;
  previous_season: number;
  teams_observed: number;
  players_observed: number;
  prior_players_not_observed: number;
  unusable_rows?: number;
  status_counts: Record<string, number>;
  team_summaries?: BBRosterSummary[];
  players: BBRoster[];
};
export type BBRosterSummary = {
  team_id: string;
  team: string;
  listed_players: number;
  returning_players: number;
  transfer_players: number;
  new_players: number;
  ambiguous_players: number;
  prior_minutes: number;
  returning_minutes: number;
  incoming_prior_minutes: number;
  represented_prior_minutes: number;
  returning_minutes_share: number | null;
  represented_prior_minutes_share: number | null;
};
export type BBImpact = {
  player_id: string;
  person_id: string;
  player: string;
  team: string;
  orapm: number | null;
  drapm: number | null;
  rapm_net: number | null;
  off_poss: number | null;
  def_poss: number | null;
  qualified: boolean;
  rank: number | null;
};
