/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PressroomRouteImport } from './routes/pressroom'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as GameplanRouteImport } from './routes/gameplan'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ScoutIndexRouteImport } from './routes/scout/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as ScoutTeamIdRouteImport } from './routes/scout/$teamId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as GamesContestIdRouteImport } from './routes/games/$contestId'

const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PressroomRoute = PressroomRouteImport.update({
  id: '/pressroom',
  path: '/pressroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const GameplanRoute = GameplanRouteImport.update({
  id: '/gameplan',
  path: '/gameplan',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutIndexRoute = ScoutIndexRouteImport.update({
  id: '/scout/',
  path: '/scout/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTeamIdRoute = ScoutTeamIdRouteImport.update({
  id: '/scout/$teamId',
  path: '/scout/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesContestIdRoute = GamesContestIdRouteImport.update({
  id: '/games/$contestId',
  path: '/games/$contestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferences': typeof ConferencesRoute
  '/film': typeof FilmRoute
  '/gameplan': typeof GameplanRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/pressroom': typeof PressroomRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/season': typeof SeasonRoute
  '/games/$contestId': typeof GamesContestIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scout/$teamId': typeof ScoutTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/games/': typeof GamesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferences': typeof ConferencesRoute
  '/film': typeof FilmRoute
  '/gameplan': typeof GameplanRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/pressroom': typeof PressroomRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/season': typeof SeasonRoute
  '/games/$contestId': typeof GamesContestIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scout/$teamId': typeof ScoutTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/games': typeof GamesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/scout': typeof ScoutIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferences': typeof ConferencesRoute
  '/film': typeof FilmRoute
  '/gameplan': typeof GameplanRoute
  '/leaders': typeof LeadersRoute
  '/login': typeof LoginRoute
  '/pressroom': typeof PressroomRoute
  '/rankings': typeof RankingsRoute
  '/recruiting': typeof RecruitingRoute
  '/season': typeof SeasonRoute
  '/games/$contestId': typeof GamesContestIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scout/$teamId': typeof ScoutTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/games/': typeof GamesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conferences'
    | '/film'
    | '/gameplan'
    | '/leaders'
    | '/login'
    | '/pressroom'
    | '/rankings'
    | '/recruiting'
    | '/season'
    | '/games/$contestId'
    | '/players/$playerId'
    | '/scout/$teamId'
    | '/teams/$teamId'
    | '/games/'
    | '/players/'
    | '/scout/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/conferences'
    | '/film'
    | '/gameplan'
    | '/leaders'
    | '/login'
    | '/pressroom'
    | '/rankings'
    | '/recruiting'
    | '/season'
    | '/games/$contestId'
    | '/players/$playerId'
    | '/scout/$teamId'
    | '/teams/$teamId'
    | '/games'
    | '/players'
    | '/scout'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conferences'
    | '/film'
    | '/gameplan'
    | '/leaders'
    | '/login'
    | '/pressroom'
    | '/rankings'
    | '/recruiting'
    | '/season'
    | '/games/$contestId'
    | '/players/$playerId'
    | '/scout/$teamId'
    | '/teams/$teamId'
    | '/games/'
    | '/players/'
    | '/scout/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConferencesRoute: typeof ConferencesRoute
  FilmRoute: typeof FilmRoute
  GameplanRoute: typeof GameplanRoute
  LeadersRoute: typeof LeadersRoute
  LoginRoute: typeof LoginRoute
  PressroomRoute: typeof PressroomRoute
  RankingsRoute: typeof RankingsRoute
  RecruitingRoute: typeof RecruitingRoute
  SeasonRoute: typeof SeasonRoute
  GamesContestIdRoute: typeof GamesContestIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ScoutTeamIdRoute: typeof ScoutTeamIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScoutIndexRoute: typeof ScoutIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressroom': {
      id: '/pressroom'
      path: '/pressroom'
      fullPath: '/pressroom'
      preLoaderRoute: typeof PressroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameplan': {
      id: '/gameplan'
      path: '/gameplan'
      fullPath: '/gameplan'
      preLoaderRoute: typeof GameplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/': {
      id: '/scout/'
      path: '/scout'
      fullPath: '/scout/'
      preLoaderRoute: typeof ScoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/$teamId': {
      id: '/scout/$teamId'
      path: '/scout/$teamId'
      fullPath: '/scout/$teamId'
      preLoaderRoute: typeof ScoutTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$contestId': {
      id: '/games/$contestId'
      path: '/games/$contestId'
      fullPath: '/games/$contestId'
      preLoaderRoute: typeof GamesContestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConferencesRoute: ConferencesRoute,
  FilmRoute: FilmRoute,
  GameplanRoute: GameplanRoute,
  LeadersRoute: LeadersRoute,
  LoginRoute: LoginRoute,
  PressroomRoute: PressroomRoute,
  RankingsRoute: RankingsRoute,
  RecruitingRoute: RecruitingRoute,
  SeasonRoute: SeasonRoute,
  GamesContestIdRoute: GamesContestIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ScoutTeamIdRoute: ScoutTeamIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScoutIndexRoute: ScoutIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
