// Client for the static analytics artifacts generated by ncaa_scraper.analytics
// (frontend/public/data/*.json). All real, public data: ESPN scores/stats/rosters,
// stats.ncaa.org play-by-play, official YouTube channels.

export type TeamIndexEntry = {
  id: number;
  name: string;
  shortName: string;
  abbrev: string;
  logo: string | null;
  color: string | null;
  altColor: string | null;
  conference: string | null;
  record: string | null;
  confRecord: string | null;
  homeRecord: string | null;
  awayRecord: string | null;
  vsApRecord: string | null;
  playoffSeed: number | null;
  apRank: number | null;
  coachesRank: number | null;
  srsRank: number | null;
  avgHomeAttendance: number | null;
  srs: number | null;
  sos: number | null;
  offEff: number | null;
  defEff: number | null;
  pace: number | null;
  ppg: number | null;
  papg: number | null;
  hasStats: boolean;
};

export type Metrics = Record<string, number | null> & {
  pace: number | null;
  offEff: number | null;
  defEff: number | null;
  efg: number | null;
  tovPct: number | null;
  orbPct: number | null;
  ftRate: number | null;
  srs: number | null;
  sos: number | null;
};

export type NarrativeItem = { text: string; metric: string; pct: number };

export type ScheduleGame = {
  gameId: number;
  date: string;
  opponent: string;
  opponentId: number | null;
  opponentLogo: string | null;
  venueTag: "home" | "away" | "neutral";
  result: "W" | "L";
  score: string;
  margin: number;
  oppSrsRank: number | null;
  confGame: boolean;
  note: string | null;
  broadcast: string | null;
};

export type KeyPlayer = {
  id: number;
  name: string;
  position: string | null;
  classYear: string | null;
  height: string | null;
  jersey: string | null;
  hometown: string | null;
  ppg?: number;
  rpg?: number;
  apg?: number;
  spg?: number;
  bpg?: number;
  mpg?: number;
  threesPg?: number;
  fgPct?: number;
  per?: number;
};

export type RosterPlayer = {
  id: number;
  name: string;
  jersey: string | null;
  position: string | null;
  height: string | null;
  weight: number | null;
  classYear: string | null;
  hometown: string | null;
};

export type RosterInfo = {
  classBreakdown: Record<string, number>;
  rosterSize: number;
  departingCount: number;
  departingShare: number;
  departingNames: { name: string; position: string | null; classYear: string | null }[];
  departingStarCount: number;
  positionalNeeds: string[];
};

export type ScoutReport = {
  identity: TeamIndexEntry & { name: string };
  metrics: Metrics;
  percentiles: Record<string, number>;
  ranks: Record<string, number>;
  narratives: { strengths: NarrativeItem[]; weaknesses: NarrativeItem[]; howToBeat: string[] };
  press: { storylines: string[]; nuggets: string[]; articleStarter: string };
  keyPlayers: KeyPlayer[];
  roster: RosterPlayer[];
  rosterInfo: RosterInfo;
  schedule: ScheduleGame[];
  qualityWins: ScheduleGame[];
  badLosses: ScheduleGame[];
  last10Record: string;
};

export type RatingsRow = {
  id: number;
  rank: number;
  name: string;
  shortName: string;
  logo: string | null;
  conference: string | null;
  record: string | null;
  apRank: number | null;
  srs: number;
  sos: number;
  offEff: number | null;
  defEff: number | null;
  pace: number | null;
  efg: number | null;
  tovPct: number | null;
  orbPct: number | null;
  ftRate: number | null;
  threePct: number | null;
  netMargin: number | null;
};

export type NewsArticle = {
  id: string;
  headline: string;
  description: string;
  published: string;
  link: string | null;
  image: string | null;
  categories: string[];
};

export type RecruitingTeam = {
  id: number;
  name: string;
  shortName: string;
  logo: string | null;
  conference: string | null;
  srsRank: number | null;
} & RosterInfo;

export type Meta = {
  season: string;
  generated: string;
  completedGames: number;
  teamsTracked: number;
  model: { homeCourtAdvantage: number; marginCap: number; sigma: number };
  leagueAverages: Record<string, number>;
  sources: { name: string; kind: string }[];
};

export type ConferenceTeamRow = {
  id: number;
  name: string;
  shortName: string;
  logo: string | null;
  seed: number | null;
  confRecord: string | null;
  record: string | null;
  srs: number | null;
  srsRank: number | null;
  apRank: number | null;
};

export type Conference = {
  id: number;
  name: string;
  teams: ConferenceTeamRow[];
  avgSrs: number | null;
  strengthRank: number;
};

export type FilmVideo = {
  videoId: string;
  title: string;
  published: string;
  channel: string;
  thumbnail: string;
  teamIds: number[];
};

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Could not load ${path} (${res.status})`);
  return (await res.json()) as T;
}

export const insights = {
  meta: () => fetchJson<Meta>("/data/meta.json"),
  teams: () => fetchJson<{ season: string; teams: TeamIndexEntry[] }>("/data/teams.json"),
  ratings: () => fetchJson<{ season: string; updated: string; board: RatingsRow[] }>("/data/ratings.json"),
  scout: (teamId: number | string) => fetchJson<ScoutReport>(`/data/scout/${teamId}.json`),
  news: () => fetchJson<{ articles: NewsArticle[] }>("/data/news.json"),
  recruiting: () => fetchJson<{ season: string; teams: RecruitingTeam[] }>("/data/recruiting.json"),
  film: () => fetchJson<{ videos: FilmVideo[] }>("/data/film.json"),
  conferences: () => fetchJson<{ season: string; conferences: Conference[] }>("/data/conferences.json"),
};

// ---------------------------------------------------------------- matchup math

function erf(x: number): number {
  // Abramowitz & Stegun 7.1.26
  const sign = x < 0 ? -1 : 1;
  const ax = Math.abs(x);
  const t = 1 / (1 + 0.3275911 * ax);
  const y =
    1 -
    ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) *
      t *
      Math.exp(-ax * ax);
  return sign * y;
}

function normCdf(x: number, sigma: number): number {
  return 0.5 * (1 + erf(x / (sigma * Math.SQRT2)));
}

export type Venue = "neutral" | "teamA" | "teamB";

export type MatchupProjection = {
  marginA: number; // expected margin for team A
  winProbA: number;
  scoreA: number;
  scoreB: number;
  pace: number;
};

export function projectMatchup(
  a: ScoutReport,
  b: ScoutReport,
  venue: Venue,
  meta: Meta,
): MatchupProjection {
  const hca = meta.model.homeCourtAdvantage;
  const sigma = meta.model.sigma;
  const srsA = a.metrics.srs ?? 0;
  const srsB = b.metrics.srs ?? 0;
  let margin = srsA - srsB;
  if (venue === "teamA") margin += hca;
  if (venue === "teamB") margin -= hca;

  const leagueOE = meta.leagueAverages.offEff ?? 105;
  const pace = ((a.metrics.pace ?? 68) + (b.metrics.pace ?? 68)) / 2;
  // efficiency-model totals, then shift so the margin matches the SRS edge
  const rawA = (pace / 100) * ((a.metrics.offEff ?? leagueOE) + (b.metrics.defEff ?? leagueOE) - leagueOE);
  const rawB = (pace / 100) * ((b.metrics.offEff ?? leagueOE) + (a.metrics.defEff ?? leagueOE) - leagueOE);
  const total = rawA + rawB;
  const scoreA = (total + margin) / 2;
  const scoreB = (total - margin) / 2;

  return {
    marginA: margin,
    winProbA: normCdf(margin, sigma),
    scoreA: Math.round(scoreA),
    scoreB: Math.round(scoreB),
    pace: Math.round(pace * 10) / 10,
  };
}

export type GameKey = { title: string; detail: string; edge: "A" | "B" | "even" };

export function buildGameKeys(a: ScoutReport, b: ScoutReport): GameKey[] {
  const keys: GameKey[] = [];
  const pa = a.percentiles;
  const pb = b.percentiles;
  const ma = a.metrics;
  const mb = b.metrics;
  const an = a.identity.shortName;
  const bn = b.identity.shortName;

  const paceGap = (ma.pace ?? 0) - (mb.pace ?? 0);
  if (Math.abs(paceGap) >= 3) {
    const fast = paceGap > 0 ? an : bn;
    const slow = paceGap > 0 ? bn : an;
    keys.push({
      title: "The tempo battle",
      detail: `${fast} wants to run (${Math.max(ma.pace ?? 0, mb.pace ?? 0)} poss/g) while ${slow} grinds (${Math.min(ma.pace ?? 0, mb.pace ?? 0)}). Whoever dictates pace tilts the game.`,
      edge: "even",
    });
  }

  const shootA = pa.efg ?? 50;
  const shootB = pb.efg ?? 50;
  if (Math.abs(shootA - shootB) >= 15) {
    const better = shootA > shootB ? an : bn;
    keys.push({
      title: "Shot-making edge",
      detail: `${better} owns the cleaner shot profile (${shootA > shootB ? ma.efg : mb.efg}% vs ${shootA > shootB ? mb.efg : ma.efg}% eFG). The other side must win possessions to compensate.`,
      edge: shootA > shootB ? "A" : "B",
    });
  }

  const handleA = pa.tovPct ?? 50; // higher percentile = takes care of ball
  const pressureB = pb.stealsPerGame ?? 50;
  if (handleA <= 30 && pressureB >= 70) {
    keys.push({
      title: `Turnovers: ${bn} pressure vs ${an} handle`,
      detail: `${an} turns it over on ${ma.tovPct}% of possessions while ${bn} averages ${mb.stealsPerGame} steals. Live-ball turnovers could decide it.`,
      edge: "B",
    });
  }
  const handleB = pb.tovPct ?? 50;
  const pressureA = pa.stealsPerGame ?? 50;
  if (handleB <= 30 && pressureA >= 70) {
    keys.push({
      title: `Turnovers: ${an} pressure vs ${bn} handle`,
      detail: `${bn} turns it over on ${mb.tovPct}% of possessions while ${an} averages ${ma.stealsPerGame} steals. Live-ball turnovers could decide it.`,
      edge: "A",
    });
  }

  const glassA = pa.orbPct ?? 50;
  const glassB = pb.orbPct ?? 50;
  if (Math.abs(glassA - glassB) >= 20) {
    const better = glassA > glassB ? an : bn;
    keys.push({
      title: "War on the glass",
      detail: `${better} rebounds ${glassA > glassB ? ma.orbPct : mb.orbPct}% of its own misses. Box-out discipline is non-negotiable for the opponent.`,
      edge: glassA > glassB ? "A" : "B",
    });
  }

  const ftA = pa.ftRate ?? 50;
  const ftB = pb.ftRate ?? 50;
  if (ftA >= 75 || ftB >= 75) {
    const better = ftA > ftB ? an : bn;
    keys.push({
      title: "The foul game",
      detail: `${better} earns ${ftA > ftB ? ma.ftRate : mb.ftRate} free-throw attempts per 100 field-goal attempts. Defending without fouling keeps this from becoming a parade to the line.`,
      edge: ftA > ftB ? "A" : "B",
    });
  }

  const threeA = ma.ptsFrom3Pct ?? 0;
  const threeB = mb.ptsFrom3Pct ?? 0;
  if (threeA > 35 || threeB > 35) {
    const reliant = threeA > threeB ? an : bn;
    keys.push({
      title: "Live by the three",
      detail: `${reliant} gets ${Math.max(threeA, threeB)}% of its points from deep. Run shooters off the line and force long, contested twos.`,
      edge: "even",
    });
  }

  if (keys.length < 3) {
    const defA = pa.defEff ?? 50;
    const defB = pb.defEff ?? 50;
    const stingier = defA > defB ? an : bn;
    keys.push({
      title: "Half-court execution",
      detail: `${stingier} brings the stingier defense (${defA > defB ? ma.defEff : mb.defEff} allowed per 100). Possessions will be precious — every empty trip hurts.`,
      edge: defA > defB ? "A" : "B",
    });
  }

  return keys.slice(0, 6);
}

// ---------------------------------------------------------------- common opponents

export type CommonOpponent = {
  opponentId: number;
  opponent: string;
  opponentLogo: string | null;
  oppSrsRank: number | null;
  aGames: ScheduleGame[];
  bGames: ScheduleGame[];
  aNet: number; // total margin for team A vs this opponent
  bNet: number;
};

export function commonOpponents(a: ScoutReport, b: ScoutReport): CommonOpponent[] {
  const byOpp = new Map<number, ScheduleGame[]>();
  for (const g of a.schedule) {
    if (g.opponentId != null && g.opponentId !== b.identity.id) {
      byOpp.set(g.opponentId, [...(byOpp.get(g.opponentId) ?? []), g]);
    }
  }
  const out: CommonOpponent[] = [];
  const bByOpp = new Map<number, ScheduleGame[]>();
  for (const g of b.schedule) {
    if (g.opponentId != null && g.opponentId !== a.identity.id) {
      bByOpp.set(g.opponentId, [...(bByOpp.get(g.opponentId) ?? []), g]);
    }
  }
  for (const [oppId, aGames] of byOpp) {
    const bGames = bByOpp.get(oppId);
    if (!bGames) continue;
    out.push({
      opponentId: oppId,
      opponent: aGames[0].opponent,
      opponentLogo: aGames[0].opponentLogo,
      oppSrsRank: aGames[0].oppSrsRank,
      aGames,
      bGames,
      aNet: aGames.reduce((s, g) => s + g.margin, 0),
      bNet: bGames.reduce((s, g) => s + g.margin, 0),
    });
  }
  return out.sort((x, y) => (x.oppSrsRank ?? 999) - (y.oppSrsRank ?? 999));
}

// ---------------------------------------------------------------- format helpers

export function pctColor(p: number | undefined | null): string {
  if (p == null) return "#9aa39c";
  if (p >= 80) return "#1f8a62";
  if (p >= 60) return "#567a62";
  if (p >= 40) return "#9aa39c";
  if (p >= 20) return "#c0843e";
  return "#c94d3f";
}

export function ordinal(n: number | null | undefined): string {
  if (n == null) return "—";
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

export function tierLabel(rank: number | null): "A" | "B" | "C" | "D" | null {
  if (rank == null) return null;
  if (rank <= 50) return "A";
  if (rank <= 100) return "B";
  if (rank <= 200) return "C";
  return "D";
}
