"use client";

import { useEffect, useMemo, useState } from "react";
import { downloadCsv, toCsv } from "../../_lib/csv";
import { fmt } from "../../_lib/format";
import { ncaaTeamBoxFilterSearch, parseNcaaTeamBoxFilters, sortNcaaTeamBox, type NcaaTeamBoxEdition, type NcaaTeamBoxFilters, type NcaaTeamBoxRow, type NcaaTeamBoxSort } from "../../_lib/ncaa-team-box";

type CatalogSeason = { season: number; generated_at: string; coverage: NcaaTeamBoxEdition["coverage"]; path: string };
type Catalog = { default_season: number; seasons: CatalogSeason[] };
const fallbackSeasons = Array.from({ length: 17 }, (_, index) => 2026 - index);
const seasonLabel = (season: number) => `${season - 1}–${String(season).slice(-2)}`;
const sortLabels: Record<NcaaTeamBoxSort, string> = { net_rtg: "Net rating", off_rtg: "Offensive rating", def_rtg: "Defensive rating", tempo: "Tempo", efg_pct: "Effective FG%", to_rate_derived: "Turnover rate", orb_pct: "Offensive rebound rate", ft_rate: "Free-throw rate", points: "Points" };
const percent = (value: number | null) => value == null ? "—" : `${fmt(value * 100, 1)}%`;

export default function NcaaTeamBox() {
  const initial = typeof window === "undefined" ? parseNcaaTeamBoxFilters("", fallbackSeasons, 2026) : parseNcaaTeamBoxFilters(window.location.search, fallbackSeasons, 2026);
  const [catalog, setCatalog] = useState<Catalog | null>(null);
  const [season, setSeason] = useState(initial.season), [query, setQuery] = useState(initial.query), [minGames, setMinGames] = useState(initial.minGames), [sort, setSort] = useState<NcaaTeamBoxSort>(initial.sort), [direction, setDirection] = useState<"asc" | "desc">(initial.direction);
  const [edition, setEdition] = useState<NcaaTeamBoxEdition | null>(null), [error, setError] = useState(""), [copied, setCopied] = useState("");
  useEffect(() => { const next = ncaaTeamBoxFilterSearch({ season, query, minGames, sort, direction }, catalog?.default_season ?? 2026); if (next !== window.location.search) window.history.replaceState(window.history.state, "", `${window.location.pathname}${next}${window.location.hash}`); }, [catalog?.default_season, direction, minGames, query, season, sort]);
  useEffect(() => { const controller = new AbortController(); fetch("/data/basketball/ncaa-team-box.json", { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error("The NCAA team archive is unavailable."); return response.json() as Promise<Catalog>; }).then((value) => { setCatalog(value); if (!value.seasons.some((entry) => entry.season === season)) setSeason(value.default_season); }).catch((reason) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, []);
  useEffect(() => { if (!catalog) return; const selected = catalog.seasons.find((entry) => entry.season === season) ?? catalog.seasons[0]; if (!selected) return; const controller = new AbortController(); setEdition(null); setError(""); fetch(selected.path, { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error("The NCAA team edition could not be loaded."); return response.json() as Promise<NcaaTeamBoxEdition>; }).then(setEdition).catch((reason) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, [catalog, season]);
  const rows = useMemo(() => { const needle = query.trim().toLowerCase(); const filtered = (edition?.teams ?? []).filter((row) => row.games >= Number(minGames) && (!needle || `${row.team} ${row.team_id} ${row.espn_team_id ?? ""}`.toLowerCase().includes(needle))); return sortNcaaTeamBox(filtered, sort, direction); }, [direction, edition, minGames, query, sort]);
  const visible = rows.slice(0, 80);
  const share = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied("Team archive link copied."); } catch { setCopied("Copy the filtered URL from your address bar."); } };
  const reset = (fn: () => void) => fn();
  return <>
    <div className="dateline eyebrow"><span>Evidence archive / NCAA team boxes</span><span>{catalog?.seasons.length ?? 17} seasons · source-derived</span></div>
    <div className="page-title"><div className="eyebrow">The NCAA team box archive</div><h1>Compare how programs<br /><em>actually played.</em></h1><p>Explore 17 seasons of NCAA-derived team box records with recomputed efficiency, tempo and Four Factor rates. Use this historical profile to learn a program&apos;s style before reading adjusted ratings or a recruiting workload signal.</p><div className="hero-actions"><a className="hero-link" href="/basketball/ratings/">Open adjusted ratings →</a></div></div>
    <div className="strip"><div><strong>{fmt(edition?.coverage.teams, 0)}</strong><span>Teams in season</span></div><div><strong>{fmt(edition?.coverage.source_rows, 0)}</strong><span>Team-game rows</span></div><div><strong>{fmt(edition?.coverage.contests, 0)}</strong><span>Source contests</span></div><div><strong>{catalog?.seasons.length ?? 17}</strong><span>Published seasons</span></div></div>
    <section className="section"><div className="section-heading"><div><div className="eyebrow">Historical team finder</div><h2>Read the profile behind the record.</h2></div><span className="note">{seasonLabel(season)} · source-native IDs</span></div>
      <div className="toolbar"><label className="control"><span>SEASON</span><select value={season} onChange={(event) => reset(() => setSeason(Number(event.target.value)))}>{(catalog?.seasons ?? fallbackSeasons.map((value) => ({ season: value } as CatalogSeason))).slice().sort((a, b) => b.season - a.season).map((entry) => <option key={entry.season} value={entry.season}>{seasonLabel(entry.season)}</option>)}</select></label><label className="control"><span>PROGRAM</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search teams or IDs" /></label><label className="control"><span>MINIMUM GAMES</span><select value={minGames} onChange={(event) => reset(() => setMinGames(event.target.value))}><option value="0">All samples</option><option value="10">10+</option><option value="20">20+</option><option value="30">30+</option></select></label><label className="control"><span>ORDER</span><select value={sort} onChange={(event) => reset(() => setSort(event.target.value as NcaaTeamBoxSort))}>{Object.entries(sortLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="control"><span>DIRECTION</span><select value={direction} onChange={(event) => reset(() => setDirection(event.target.value as "asc" | "desc"))}><option value="desc">Highest first</option><option value="asc">Lowest first</option></select></label><button className="button secondary" type="button" onClick={share}>Copy team link</button></div>
      {copied && <p role="status">{copied}</p>}
      {error ? <p role="alert" className="status-error">{error}</p> : !edition ? <p role="status" className="empty">Loading NCAA team profiles…</p> : <><div className="section-heading" style={{ marginBottom: 20 }}><p>{fmt(rows.length, 0)} matching teams · showing {fmt(visible.length, 0)}</p><button className="button secondary" type="button" onClick={() => downloadCsv(`ncaa-team-box-${season}.csv`, toCsv(["Season", "Rank", "Program", "NCAA team ID", "Games", "Net rating", "Offensive rating", "Defensive rating", "Tempo", "eFG%", "Def. eFG%", "Turnover rate", "Offensive rebound rate", "FT rate", "Points"], rows.map((row) => [seasonLabel(row.season), row.net_rank, row.team, row.team_id, row.games, row.net_rtg, row.off_rtg, row.def_rtg, row.tempo, row.efg_pct == null ? null : row.efg_pct * 100, row.def_efg_pct == null ? null : row.def_efg_pct * 100, row.to_rate_derived == null ? null : row.to_rate_derived * 100, row.orb_pct == null ? null : row.orb_pct * 100, row.ft_rate == null ? null : row.ft_rate * 100, row.points])))}>Download CSV ↓</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Rank</th><th>Program</th><th className="numeric">Games</th><th className="numeric">Net</th><th className="numeric">Off.</th><th className="numeric">Def.</th><th className="numeric">Tempo</th><th className="numeric">eFG%</th><th className="numeric">Def. eFG%</th><th className="numeric">TO rate</th><th className="numeric">ORB%</th><th className="numeric">FTR</th><th className="numeric">Points</th></tr></thead><tbody>{visible.map((row: NcaaTeamBoxRow) => <tr key={`${row.season}-${row.team_id}`}><td className="rank-number">{row.net_rank}</td><td><strong>{row.team}</strong><small>NCAA {row.team_id}{row.espn_team_id ? ` · ESPN ${row.espn_team_id}` : ""}</small></td><td className="numeric">{fmt(row.games, 0)}</td><td className="numeric">{fmt(row.net_rtg)}</td><td className="numeric">{fmt(row.off_rtg)}</td><td className="numeric">{fmt(row.def_rtg)}</td><td className="numeric">{fmt(row.tempo)}</td><td className="numeric">{percent(row.efg_pct)}</td><td className="numeric">{percent(row.def_efg_pct)}</td><td className="numeric">{percent(row.to_rate_derived)}</td><td className="numeric">{percent(row.orb_pct)}</td><td className="numeric">{percent(row.ft_rate)}</td><td className="numeric">{fmt(row.points, 0)}</td></tr>)}</tbody></table></div>{!visible.length && <p className="empty">No team profiles match these filters.</p>}</>}
    </section>
    <section className="section paper-panel"><h2>How to read the profile.</h2><p>Ratings are descriptive, unadjusted season aggregates from the NCAA team-box release. Offensive and defensive efficiency are points per source possession × 100; tempo is the mean of offensive and defensive possessions per game. Four Factor rates are recomputed from source counts, and the full source totals and source averages remain in each downloadable edition.</p><p>This archive is separate from Silvermine&apos;s opponent-adjusted ratings, forecasts and recruiting observations. Team names and IDs remain source-native; a source row does not establish current membership, eligibility or a unique program across every historical season. Source: <a href="https://github.com/sportsdataverse/sportsdataverse-data" target="_blank" rel="noreferrer">SportsDataverse</a>, CC BY 4.0.</p></section>
  </>;
}
